// Type definitions
type StellarConfig = {
  NETWORK_PASSPHRASE: string;
  HORIZON_URL: string;
  SOROBAN_RPC_URL: string;
  MAX_FEE: string;
  SOURCE_ACCOUNT: SignerKeypair;
};

type ProjectConfig = {
  ID: string;
  TITLE: string;
};

type TokenContractConfig = {
  NATIVE: string;
  USDC: string;
};

type SignerKeypair = {
  PRIVATE_KEY: string;
  PUBLIC_KEY: string;
};

export const STELLAR: StellarConfig = {
  NETWORK_PASSPHRASE: "Test SDF Network ; September 2015",
  HORIZON_URL: "https://horizon-testnet.stellar.org",
  SOROBAN_RPC_URL: "https://soroban-testnet.stellar.org",
  MAX_FEE: "10000",
  SOURCE_ACCOUNT: {
    PRIVATE_KEY: "SAARF2ZWAHZJMKA6LXIFVNIHUBEUTMKV5NWCCUZV6ORPKLUK6RSOYZ4D",
    PUBLIC_KEY: "GAX7FKBADU7HQFB3EYLCYPFKIXHE7SJSBCX7CCGXVVWJ5OU3VTWOFEI5",
  },
};

export const PROJECT: ProjectConfig = {
  ID: "meridian-2024-smart-wallet",
  TITLE: "Smart Wallet",
};

export const TOKEN_CONTRACT: TokenContractConfig = {
  NATIVE: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
  USDC: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
};

export const G_ACCOUNT_ED25519_SIGNER: SignerKeypair = {
  PUBLIC_KEY: "GC4BDFONC3EHB5VZCI5BYF2OJEXX7LCU7JROUYF5RRY62FAWMF4GFV3X",
  PRIVATE_KEY: "SB5HCY4MPV6CNFOPNCTZ5IOU5YGKMYJCASA346NHPLYG4W5ULBTTLYLL",
};

export const C_ACCOUNT_ED25519_SIGNER: SignerKeypair = {
  PUBLIC_KEY: "CCU5TWNSNHKCZLMQOYYKOBHN45K23A6JFD3UABZJ7MMFSAUMKAC5P4FT",
  PRIVATE_KEY: "SAARF2ZWAHZJMKA6LXIFVNIHUBEUTMKV5NWCCUZV6ORPKLUK6RSOYZ4D",
};
