// export const Constants = {
//   Stellar: {
//     NETWORK_PASSPHRASE: "Test SDF Network ; September 2015",
//     HORIZON_URL: "https://horizon-testnet.stellar.org",
//     SOROBAN_RPC_URL: "https://soroban-testnet.stellar.org",
//     MAX_FEE: "10000",
//     SOURCE_ACCOUNT_PUBLIC_KEY: "GCBDDD6CRVRQSS5YRO3FCS7GYREY6UEXF6B2WEDQS4INX53J2VDPV3CF",
//     SOURCE_ACCOUNT_PRIVATE_KEY: "SBQOPFIHZ5LMQTPFNU67N7CXV7LQSPXSZGYJVXREGEE3Z7BYBXD5RJTG",
//   },
//   Accounts: {
//     ACCOUNT_A_PUBLIC_KEY: "GADKQWEE3DEXCZNBLSOHATXO53UMTTXFOZZHVJODLTEKM3NUK2PBX6ZH",
//     ACCOUNT_A_PRIVATE_KEY: "SAOAIWY4T4M5F4BR4CKYNYGXFDMIY3R2G3JAKWTK7ABCNQDLTVUEFLEX",
//     ACCOUNT_B_SECRET_KEY: "SCF6RKYTBGYQB3JPD2VWXDXBD6GDV6MUZ6YHDL2JYZ2JNR3A7SBPOWPZ",
//   },
//   ContractIDs: {
//     TOKEN_NATIVE: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
//     TOKEN_USDC: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
//   },
//   Project: {
//     ID: "meridian-2024-smart-wallet",
//     TITLE: "Smart Wallet",
//   },
// };

export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
export const HORIZON_URL = "https://horizon-testnet.stellar.org";
export const SOROBAN_RPC_URL = "https://soroban-testnet.stellar.org";
export const MAX_FEE = "10000";

export const ACCOUNT_A_PUBLIC_KEY = "GC4BDFONC3EHB5VZCI5BYF2OJEXX7LCU7JROUYF5RRY62FAWMF4GFV3X";
export const ACCOUNT_A_PRIVATE_KEY = "SB5HCY4MPV6CNFOPNCTZ5IOU5YGKMYJCASA346NHPLYG4W5ULBTTLYLL"; // GC4BDFONC3EHB5VZCI5BYF2OJEXX7LCU7JROUYF5RRY62FAWMF4GFV3X
export const ACCOUNT_B_SECRET_KEY = "SCF6RKYTBGYQB3JPD2VWXDXBD6GDV6MUZ6YHDL2JYZ2JNR3A7SBPOWPZ"; // GBAZJLSXCBSENLMRBHBT6DFO73TG5BK7MKN2WJSJJ2OVGHA65BXPRORD

export const SOURCE_ACCOUNT_PUBLIC_KEY = "GAX7FKBADU7HQFB3EYLCYPFKIXHE7SJSBCX7CCGXVVWJ5OU3VTWOFEI5";
export const SOURCE_ACCOUNT_SECRET_KEY = "SAARF2ZWAHZJMKA6LXIFVNIHUBEUTMKV5NWCCUZV6ORPKLUK6RSOYZ4D"; // GAX7FKBADU7HQFB3EYLCYPFKIXHE7SJSBCX7CCGXVVWJ5OU3VTWOFEI5
export const ALICE_ACCOUNT_SECRET_KEY = "SAARF2ZWAHZJMKA6LXIFVNIHUBEUTMKV5NWCCUZV6ORPKLUK6RSOYZ4D"; // GAX7FKBADU7HQFB3EYLCYPFKIXHE7SJSBCX7CCGXVVWJ5OU3VTWOFEI5

// export const SOURCE_ACCOUNT_SECRET_KEY = "SBQOPFIHZ5LMQTPFNU67N7CXV7LQSPXSZGYJVXREGEE3Z7BYBXD5RJTG"; // GCBDDD6CRVRQSS5YRO3FCS7GYREY6UEXF6B2WEDQS4INX53J2VDPV3CF
export const PROJECT_ID = "meridian-2024-smart-wallet";
export const PROJECT_TITLE = "Smart Wallet";

export const USDC_CONTRACT_ID = "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA";
export const NATIVE_CONTRACT_ID = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";
